### ISSUE TITLE
Don't transmit the secret key to google

### ISSUE THREAD

**Issue by ccoenen** [jjssoftware/ESP8266TOTP#1]
In this piece of code, you [generate a URL](https://github.com/jjssoftware/ESP8266TOTP/blob/97d0121f64463b8af54a3981ebb875147fdac716/ESP8266TOTP.cpp#L135-L140) that generates a QR-Code. The user will load this URL and is effectively transmitting their secret key to Google.

I think this is not ideal.

I believe the QR-Code should either be generated onthe ESP or the client (there are JS implementatations which could be included), but not by a third party.

**Comment by bebo-dot-dev** [comment]
You're right I agree, I'll take a look at removing this.

Personally I'll probably end up going with a JS QR code generator implementation rather than an ESP side version.

**Comment by bebo-dot-dev** [comment]
This should do it: https://github.com/jjssoftware/ESP8266TOTP/commit/df0434a1089f4bf99ae01cc0558f75841d32d63a

Less is more as they say ;)

**Comment by bebo-dot-dev** [comment]
Thanks for the peer review, it's much appreciated. Closing this one down.
