### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by steffenmllr** [jjssoftware/ESP8266TOTP#2]
Hey there! I was trying to make myself a small oled display that displays the current OTP Code for a given account. 

Since my C++ Skill are non-existent I was reading through your code (Thanks you, I learned a lot 😄 ) and was asking myself if it is possible to pass in the totp secret a a string into your `ESP8266TOTP::GetTOTPToken` function ? 

I store the totp configuration [like this](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) `otpauth://totp/ACME%20Co:john.doe@email.com?secret=HXDMVJECJJWSRB3HWIZR4IFUGFTMXBOZ&issuer=ACME%20Co&algorithm=SHA1&digits=6&period=30` and my function [looks like this](https://gist.github.com/steffenmllr/14ba69e13d2fe00c62adf3bb2daf5d21#file-ttop-cpp-L68-L111).

**Comment by bebo-dot-dev** [comment]
Hi there sorry for the delay replying, I'm not sure why github didn't send me a notification email about this issue..

Back when I originally pushed this code, I did include a basic usage example sketch here: https://github.com/jjssoftware/ESP8266TOTP/blob/master/examples/basic.ino

The general idea with this sample is that:

1. code in ESP8266TOTP::GetNewKey generates a brand new super secret key only known to the device the key is generated upon. This secret is temporarily stored in data.keyBytes where data is of the type totpData: https://github.com/jjssoftware/ESP8266TOTP/blob/c76366ffa95cc1c858b7ce40e62583e56229187f/ESP8266TOTP.h#L33-L36
2. For a given secret key, a OTP one time password can be calculated (if necessary) using ESP8266TOTP::GetTOTPToken: https://github.com/jjssoftware/ESP8266TOTP/blob/master/examples/basic.ino#L27 (note the example uses a static point in time EPOCH value and a real application would use the current point in time EPOCH by implementing e.g. an NTP client
3. If a OTP was supplied to the application in some way (via serial input, HTTP POST etc) after perhaps having been calculated in the Google Authenticator app, then a comparison can be performed via ESP8266TOTP::IsTokenValid to verify if the supplied OTP is valid for the device according to the currently stored secret key: https://github.com/jjssoftware/ESP8266TOTP/blob/master/examples/basic.ino#L30

That's the general idea, please let me know if this makes sense.

I do use this stuff myself in my own ESP8266 firmware so I'm able to confirm it all works and there's a blog article written up with screenshots etc here: https://jjssoftware.github.io/esp8266-rfc6238-totp/

**Comment by steffenmllr** [comment]
Thanks for taking the time to reply. I managed to get everything working. Although I never figured out how to pass in the key as a string. I just switched to a uint8_t and everything worked fine...

**Comment by bebo-dot-dev** [comment]
I'm happy to hear you got it working. Now that I've re-read your question (properly, sorry) I think it would have been a more useful and targeted answer if I'd replied with this:

```
/*
 * returns an indicator whether the totp value in the local suppliedTotp string variable 
 * matches the current otp calculated from the current epoch offset and secret key bytes
 */
bool ICACHE_FLASH_ATTR isTotpTokenValid() {

    String suppliedTotp = "<your_totp>"; //e.g. "155194"

    char *endptr;
    int suppliedOtp = strtoul(suppliedTotp.c_str(), &endptr, 10);

    //check the supplied OTP against the current secret key
    return ((*endptr == '\0') &&
            (ESP8266TOTP::IsTokenValid(
                    NetworkSvcMngr.ntpManager->getUtcTimeNow(),
                    appConfigData.otp.keyBytes,
                    suppliedOtp)));
}
```

**Comment by steffenmllr** [comment]
Ahh ok `strtoul` was what I was looking for. Thanks for the explanation!
